name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ziminga/ziming-blog
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        username: root
        password: ${{ secrets.TENCENT_CLOUD_SECRET_KEY}}
        port: 22
        script: |
          docker pull ziminga/ziming-blog
          kubectl set image deployments/demo-frontend frontend-app=ziminga/ziming-blog:latest

